language: node_js
node_js:
  - 10

install: npm install

script:
  - npm run lint
  - npm run build

cache:
  yarn: true
  directories:
    - "node_modules"

before_deploy:
  - tar cfvz bcd.tar.gz dist

deploy:
  provider: releases
  skip_cleanup: true
  file: bcd.tar.gz
  api_key: $GITHUB_TOKEN 
  on:
    all_branches: true
    tag: true
    condition: "$TRAVIS_TAG =~ ^[0-9\.]+$"
