name: Deploy
on:
 push:
   tags:
     - "*.*.*"

jobs:
  build:
    name: Netlify
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@master
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install deps and build
        run: |
          npm install
          npm run build
        env:
          VUE_APP_SENTRY_URI: ${{ secrets.VUE_APP_SENTRY_URI }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          production-deploy: true
          github-deployment-environment: production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
