on: push
name: Test

jobs:
  build:
    name: Install deps, lint, and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: install, lint and build
      run: |
        npm i
        npm run lint
        npm run build
